- name: add {{ PUBLIC_IP }} 443 firewall rule
  local_action:
    module: vultr_firewall_rule
    group: '{{ SHADOWSOCKS_VULRE_FW_NAME }}'
    protocol: tcp
    start_port: 443
    #    end_port: '{{ item.e_port }}'
    cidr: '{{ PUBLIC_IP }}'
    state: present


    