---
# tasks file for vultr-firewall
- name: ensure '{{ SHADOWSOCKS_VULRE_FW_NAME }}' firewall group is present
  local_action:
    module: vultr_firewall_group
    name: '{{ SHADOWSOCKS_VULRE_FW_NAME }}'
    state: present

- include: icmp.yml
- include: http.yml
- include: https.yml
- include: ssh.yml
- include: delete.yaml
