- name: Restart server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to restart successfully
  local_action: wait_for
    host="{{ groups['vultr'][0] }}"
    port=22
    delay=1
    timeout=30

- name: Get last two reboots
  command: /usr/bin/last reboot | head -2
  register: last

- name: Show last two reboots
  debug: var=last.stdout_lines