- name: Create swapfile
  command: "dd if=/dev/zero of={{ swap_path }} bs={{ dd_bs_size_mb }}M count={{ swap_count }} creates={{ swap_path }}"
  register: write_swapfile

- name: Set swapfile permissions
  file: path="{{ swap_path }}" mode=600

- name: Build swapfile
  command: "mkswap {{ swap_path }}"
  register: create_swapfile
  when: write_swapfile.changed

- name: Enable swapfile
  command: "swapon {{ swap_path }}"
  when: create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swap_path }}   none    swap    sw    0   0" state=present

# - name: Configure swappiness
#   lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
#   notify: sysctl
#   when: swappiness != false

# - name: Configure vm.vfs_cache_pressure
#   lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
#   notify: sysctl
#   when: vfs_cache_pressure != false

